# Generated by Django 4.1.1 on 2022-09-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="title",
            new_name="exercise_text",
        ),
    ]
