# Generated by Django 4.1.1 on 2022-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0008_alter_test_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="stdout",
            field=models.CharField(default="", max_length=255),
        ),
    ]
