# Generated by Django 4.1.1 on 2022-09-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0009_testresult_stdout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testresult",
            old_name="file",
            new_name="submission",
        ),
    ]
