# Generated by Django 4.1.1 on 2022-10-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0011_alter_testresult_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="running",
            field=models.BooleanField(default=False),
        ),
    ]
