# Generated by Django 4.1.1 on 2022-10-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0012_testresult_running"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
