# Generated by Django 4.1.2 on 2022-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0018_alter_submission_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
