# Generated by Django 4.1.2 on 2022-11-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0019_submission_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="running",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="success",
        ),
        migrations.AddField(
            model_name="testresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
