# Generated by Django 4.1.2 on 2022-11-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0020_remove_testresult_running_remove_testresult_success_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="stdout",
            field=models.TextField(default=""),
        ),
    ]
