# Generated by Django 4.1.4 on 2023-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0021_alter_testresult_stdout"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
