# Generated by Django 4.1.2 on 2023-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0022_submission_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="stdin",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="test",
            name="stdout",
            field=models.TextField(blank=True, default=""),
        ),
    ]
