# Generated by Django 4.1.4 on 2023-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0023_alter_test_stdin_alter_test_stdout'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='coefficient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
