# Generated by Django 4.1.4 on 2023-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0023_alter_test_stdin_alter_test_stdout"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="cg_mem",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="test",
            name="time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="test",
            name="wall_time",
            field=models.FloatField(default=0),
        ),
    ]
