# Generated by Django 4.1.4 on 2023-04-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0024_test_cg_mem_test_time_test_wall_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="cg_mem",
            new_name="cgmem",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="wall_time",
            new_name="walltime",
        ),
        migrations.AddField(
            model_name="test",
            name="exitcode",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="test",
            name="exitsig",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="test",
            name="killed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="test",
            name="statuscode",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="test",
            name="statusmessage",
            field=models.TextField(blank=True, default=""),
        ),
    ]
