# Generated by Django 4.1.4 on 2023-08-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0024_add_grading_system"),
        ("runner", "0024_alter_test_unique_together"),
    ]

    operations = []
