# Generated by Django 4.1.4 on 2023-04-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0025_rename_cg_mem_test_cgmem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="detail",
            field=models.TextField(blank=True, default=""),
        ),
    ]
