# Generated by Django 4.1.4 on 2023-08-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0026_submission_ignore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="ignore",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
