# Generated by Django 4.1.4 on 2023-08-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0027_alter_submission_ignore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="coefficient",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
