# Generated by Django 4.1.4 on 2023-11-20 13:53

from django.db import migrations, models
import runner.models


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0028_alter_test_coefficient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(upload_to=runner.models.Submission.get_file_name),
        ),
    ]
