# Generated by Django 4.1.4 on 2023-10-05 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0028_alter_test_coefficient"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="test",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="test",
            name="exercise",
        ),
        migrations.AlterUniqueTogether(
            name="testresult",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="exercise_test",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="submission",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.DeleteModel(
            name="TestResult",
        ),
    ]
