# Generated by Django 4.1.2 on 2022-11-22 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_remove_course_owner_course_owners"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tutors",
            field=models.ManyToManyField(
                related_name="%(class)s_courses_tutors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
