# Generated by Django 4.1.2 on 2022-11-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_course_tutors"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[
                    ("ada", "Ada"),
                    ("c", "C"),
                    ("c++", "C++"),
                    ("c#", "C#"),
                    ("d", "D"),
                    ("go", "Go"),
                    ("haskell", "Haskell"),
                    ("java", "Java"),
                    ("javascript", "JavaScript"),
                    ("lua", "Lua"),
                    ("ocaml", "OCaml"),
                    ("pascal", "Pascal"),
                    ("perl", "Perl"),
                    ("php", "PHP"),
                    ("prolog", "Prolog"),
                    ("python", "Python"),
                    ("ruby", "Ruby"),
                    ("rust", "Rust"),
                    ("scheme", "Scheme"),
                ],
                default="python",
                max_length=10,
            ),
        ),
    ]
