# Generated by Django 4.1.4 on 2022-12-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_course_tutors"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="join_code",
            field=models.CharField(default="00000000", max_length=8),
        ),
    ]
