# Generated by Django 4.1.4 on 2022-12-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_course_join_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="join_code_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
