# Generated by Django 4.1.4 on 2023-03-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_course_join_code_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="prefix",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="suffix",
            field=models.TextField(blank=True),
        ),
    ]
