# Generated by Django 4.1.4 on 2023-07-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_exercise_prefix_exercise_suffix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
