# Generated by Django 4.1.4 on 2023-06-20 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0010_exercise_prefix_exercise_suffix"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="%(class)s_students", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
