# Generated by Django 4.1.4 on 2023-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_studentgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="auto_groups",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="auto_groups_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="course",
            name="auto_groups_type",
            field=models.CharField(
                choices=[("alphabetical", "Alphabetical"), ("random", "Random")],
                default="random",
                max_length=12,
            ),
        ),
    ]
