# Generated by Django 4.1.4 on 2023-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_course_description_alter_course_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="session",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
