# Generated by Django 4.1.4 on 2023-07-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_exercise_description_alter_exercise_title_and_more"),
        ("api", "0012_course_auto_groups_course_auto_groups_number_and_more"),
    ]

    operations = []
