# Generated by Django 4.1.4 on 2023-07-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_merge_20230711_0858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="auto_groups_type",
            field=models.CharField(
                choices=[("alphabetical", "Alphabetical")],
                default="alphabetical",
                max_length=12,
            ),
        ),
    ]
