# Generated by Django 4.1.4 on 2023-07-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_course_auto_groups_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="auto_groups",
            new_name="auto_groups_enabled",
        ),
        migrations.AddField(
            model_name="course",
            name="groups_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="auto_groups_number",
            field=models.IntegerField(default=2),
        ),
    ]
