# Generated by Django 4.1.4 on 2023-07-18 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0015_rename_auto_groups_course_auto_groups_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="auto_groups_number",
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
