# Generated by Django 4.1.4 on 2023-07-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_course_groups_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
