# Generated by Django 4.1.4 on 2023-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_add_grading_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[
                    ("asm", "Assembly"),
                    ("bash", "Bash"),
                    ("basic", "Basic"),
                    ("c", "C"),
                    ("cpp", "C++"),
                    ("csharp", "C#"),
                    ("clojure", "Clojure"),
                    ("cobol", "Cobol"),
                    ("commonlisp", "Common Lisp"),
                    ("d", "D"),
                    ("elixir", "Elixir"),
                    ("erlang", "Erlang"),
                    ("executable", "Executable"),
                    ("fortran", "Fortran"),
                    ("fsharp", "F#"),
                    ("go", "Go"),
                    ("groovy", "Groovy"),
                    ("haskell", "Haskell"),
                    ("java", "Java"),
                    ("javascript", "JavaScript"),
                    ("kotlin", "Kotlin"),
                    ("lua", "Lua"),
                    ("objectivec", "Objective-C"),
                    ("ocaml", "OCaml"),
                    ("octave", "Octave"),
                    ("pascal", "Pascal"),
                    ("perl", "Perl"),
                    ("php", "PHP"),
                    ("prolog", "Prolog"),
                    ("python", "Python"),
                    ("r", "R"),
                    ("ruby", "Ruby"),
                    ("rust", "Rust"),
                    ("scala", "Scala"),
                    ("sql", "SQL"),
                    ("swift", "Swift"),
                    ("typescript", "TypeScript"),
                    ("vbnet", "VB.NET"),
                ],
                default="python",
                max_length=10,
            ),
        ),
    ]
