# Generated by Django 4.1.4 on 2023-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_course_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
