# Generated by Django 4.1.4 on 2023-11-21 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_session_deadline_session_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="deadline",
        ),
    ]
