# Generated by Django 4.1.4 on 2023-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_remove_session_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="deadline_type",
            field=models.CharField(
                choices=[("soft", "Soft"), ("hard", "Hard")],
                default="soft",
                max_length=4,
            ),
        ),
    ]
