# Generated by Django 4.1.4 on 2023-11-27 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_session_deadline_session_deadline_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="late_penalty",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("late_penalty__isnull", True),
                    models.Q(("late_penalty__lte", 1.0), ("late_penalty__gte", 0.0)),
                    _connector="OR",
                ),
                name="late_penalty_between_0_and_1",
            ),
        ),
    ]
