# Generated by Django 4.1.4 on 2023-11-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_session_late_penalty_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="session",
            name="late_penalty_between_0_and_1",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="grade",
            new_name="coefficient",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="grade",
            new_name="coefficient",
        ),
        migrations.RemoveField(
            model_name="session",
            name="late_penalty",
        ),
        migrations.AddField(
            model_name="course",
            name="grade_max",
            field=models.FloatField(default=20),
        ),
    ]
