# Generated by Django 4.1.4 on 2023-11-28 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_alter_exercise_coefficient_alter_session_coefficient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="coefficient",
        ),
    ]
