# Generated by Django 4.1.4 on 2023-12-04 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_remove_course_grade_max_remove_exercise_coefficient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="auto_groups_type",
        ),
        migrations.AddField(
            model_name="course",
            name="late_penalty",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
