# Generated by Django 4.2.7 on 2023-12-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_remove_course_auto_groups_type_course_late_penalty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="api.session",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="api.course",
            ),
        ),
    ]
