# Generated by Django 4.2.7 on 2023-12-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_alter_exercise_session_alter_session_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.session"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
    ]
