# Generated by Django 4.2.7 on 2024-01-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_alter_exercise_session_alter_session_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="teacher_files",
            field=models.FileField(blank=True, upload_to="teacher_files/"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="type",
            field=models.CharField(
                choices=[("single", "Single"), ("multiple", "Multiple")],
                default="single",
                max_length=8,
            ),
        ),
    ]
