# Generated by Django 4.2.7 on 2024-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_exercise_teacher_files_exercise_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="teacher_files",
            field=models.FileField(blank=True, null=True, upload_to="teacher_files/"),
        ),
    ]
