# Generated by Django 4.1.1 on 2022-09-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0005_test_rename_file_file_stored_file_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="Submission",
        ),
    ]
