# Generated by Django 4.1.1 on 2022-09-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0006_rename_file_submission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="stored_file",
            new_name="file",
        ),
    ]
