# Generated by Django 4.1.1 on 2022-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0007_rename_stored_file_submission_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="rules",
            field=models.TextField(),
        ),
    ]
