# Generated by Django 4.1.1 on 2022-09-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0010_rename_file_testresult_submission"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testresult",
            unique_together={("submission", "exercise_test")},
        ),
    ]
